Diagnostics:
  ClangTidy:
    Add: "*"
    Remove:
      - "altera*"
      - "android*"
      - "bugprone-easily-swappable-parameters"
      - "cert-dcl16-c"
      - "cert-msc*"
      - "concurrency-mt-unsafe"
      - "fuchsia*"
      - "hicpp-uppercase-literal-suffix"
      - "llvmlibc-*"
      - "readability-identifier-length"
      - "readability-uppercase-literal-suffix"
