Diagnostics:
  ClangTidy:
    Add: "*"
    Remove:
      - "altera*"
      - "bugprone-easily-swappable-parameters"
      - "cert-msc*"
      - "concurrency-mt-unsafe"
      - "hicpp-uppercase-literal-suffix"
      - "llvmlibc-restrict-system-libc-headers"
      - "readability-identifier-length"
      - "readability-uppercase-literal-suffix"
