[colors.cursor]
cursor = "#61afef"
text = "#020202"

[colors.normal]
black = "#020202"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#c678dd"
red = "#e06c75"
white = "#eeeeee"
yellow = "#d19a66"

[colors.primary]
background = "#020202"
foreground = "#eeeeee"

[cursor.style]
blinking = "Never"
shape = "Beam"

[font]
size = 11

[font.normal]
family = "Iosevka Term SS05"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollHalfPageUp"
key = "U"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollHalfPageDown"
key = "D"
mods = "Alt"
