theme = "onedarkest"

[editor]
true-color = true
completion-trigger-len = 1
idle-timeout = 0
scrolloff = 999
soft-wrap.enable = true
file-picker.git-exclude = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
goto-reference-include-declaration = false

[keys.normal]
X = ["extend_line_up", "extend_to_line_bounds"]
A-e = "expand_selection"
A-w = "shrink_selection"
A-n = "select_prev_sibling"
A-m = "select_next_sibling"
A-space = "collapse_selection"
g.q = ":reflow"
"(" = ["goto_prev_diag", "code_action"]
")" = ["goto_next_diag", "code_action"]

[keys.normal.space]
q.q = ":xa"
q.Q = ":qa!"
c.s = ":update"
"," = ":bc"
t.a = ":theme acme"
t.i = ":theme onelight"
t.o = ":theme onedarkest"
t.m = ":theme modus_operandi"
t.v = ":theme modus_vivendi"
t.p = ":theme pink"

[keys.insert]
C-space = "completion"
